python KernelCoder/main.py \
    --run_name reasoning_bank_parallel_4 \
    --benchmark KernelBench \
    --num_epochs 1 \
    --batch_size 1 \
    --num_parallel 4 \
    --num_iterations 1 \
    --server_type litellm \
    --model_name anthropic/claude-sonnet-4-5-20250929 \
    --max_tokens 8192 \
    --temperature 0.7 \
    --hardware A6000_babel \
    --num_eval_devices 4
