python KernelCoder/test_time_scaling.py \
    --run_name test \
    --method best-of-N \
    --num_parallel 2 \
    --num_samples 1 \
    --num_iterations 1 \
    --server_type litellm \
    --model_name anthropic/claude-haiku-4-5-20251001 \
    --max_tokens 8192 \
    --temperature 0.7 \
    --hardware A6000_babel \
    --num_eval_devices 2 \
    --test \
