python KernelCoder/test_time_scaling.py \
    --run_name test_time_scaling_iterative_refinement_4 \
    --method "iterative refinement" \
    --num_parallel 1 \
    --num_iterations 4 \
    --server_type litellm \
    --model_name anthropic/claude-haiku-4-5-20251001 \
    --max_tokens 8192 \
    --temperature 0.7 \
    --hardware A6000_babel \
    --num_eval_devices 3 \
